# buildspec.yml
version: 0.2
env:
  variables:
    AWS_DEFAULT_REGION: ap-northeast-2
    AWS_ACCOUNT_ID: 289850138235
    JWT_SECRET: $JWT_SECRET
    DATABASE_URL: $DATABASE_URL
    DATABASE_USERNAME: $DATABASE_USERNAME
    DATABASE_PASSWORD: $DATABASE_PASSWORD
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - mkdir -p ./hwpSpring/src/main/resources/
      - |
        echo "jwt:" > ./hwpSpring/src/main/resources/application.yml
        echo "  secret: $JWT_SECRET" >> src/main/resources/application.yml
        echo "spring:" >> src/main/resources/application.yml
        echo "  profiles:" >> src/main/resources/application.yml
        echo "    include: aws" >> src/main/resources/application.yml
        echo "    active: dev" >> src/main/resources/application.yml
        echo "  datasource:" >> src/main/resources/application.yml
        echo "    url: $DATABASE_URL" >> src/main/resources/application.yml
        echo "    username: $DATABASE_USERNAME" >> src/main/resources/application.yml
        echo "    password: $DATABASE_PASSWORD" >> src/main/resources/application.yml
        echo "    driver-class-name: org.mariadb.jdbc.Driver" >> src/main/resources/application.yml
        echo "  jpa:" >> src/main/resources/application.yml
        echo "    properties:" >> src/main/resources/application.yml
        echo "      hibernate:" >> src/main/resources/application.yml
        echo "        show_sql: true" >> src/main/resources/application.yml
        echo "        format_sql: true" >> src/main/resources/application.yml
        echo "        dialect: org.hibernate.dialect.MariaDBDialect" >> src/main/resources/application.yml
        echo "    hibernate:" >> src/main/resources/application.yml
        echo "      ddl-auto: update" >> src/main/resources/application.yml
    commands:
      - echo Building the Spring Project...
      - cd hwpSpring
      - cat ./src/main/resources/application.yml
      - chmod +x ./gradlew
      - ./gradlew clean build -x test
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t hwp .
      - docker tag hwp:latest 289850138235.dkr.ecr.ap-northeast-2.amazonaws.com/hwp:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 289850138235.dkr.ecr.ap-northeast-2.amazonaws.com/hwp:latest
artifacts:
  files:
    - hwpSpring/appspec.yml
    - hwpSpring/scripts/**