spring:
  security:
    user:
      name: test
      password: dummy
    headers:
      frame: false
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb

#logging:
#  level:
#    org:
#      springframework: trace

server:
  tomcat:
    use-relative-redirects: true

jwt:
  secret: 3c562b8f7a091086aa57eb923892625adc7753cdbcb06c8411657c48829a8444

  #spring.h2.console.enabled=true
  #spring.datasource.url=jdbc:h2:mem:testdb